quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=quarkus
quarkus.keycloak.admin-client.client-id=quarkus-client
quarkus.keycloak.admin-client.client-secret=secret
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

# Keycloak DevServices
# https://ja.quarkus.io/guides/dev-services#keycloak
# https://ja.quarkus.io/guides/security-openid-connect-dev-services.html
# Dev UI http://localhost:8080/q/dev-ui
quarkus.keycloak.devservices.enabled=true
quarkus.keycloak.devservices.port=8081
quarkus.keycloak.devservices.realm-name=quarkus
quarkus.keycloak.devservices.realm-path=realm.json
